config/routes.rb
Auctioneer::Application.routes.draw do
  resources :item_aliases

  get '/auctions/search' => 'auction#search', :as => 'auction_search'
  resources :auction
  resources :item
  resources :logs
  root :to => 'auction#index'

end

app/models/auction.rb
require 'digest/md5'
class Auction < ActiveRecord::Base
  belongs_to :item
  validates_presence_of :time
  validates_presence_of :price
  validates_presence_of :item_id
  validates_presence_of :player
  
  scope :not_hidden, {:conditions => {:hidden => false}}
  
  def digest
    i = self.item
    if i.blank?
      return
    end
    Digest::MD5.hexdigest("#{self.time.to_s}#{i.id}#{self.price}#{self.player}")
  end
  
  before_create :gen_hash
  
  def hide!
    self.hidden = true
    save
  end
  
  def gen_hash
    self.hash_data = digest
  end
  
end

app/controllers/admin/auctions_controller.rb
class Admin::AuctionsController < Admin::ResourcesController
end

app/controllers/auction_controller.rb
require 'auction_parser'
class AuctionController < ApplicationController
  
  def create
    folder = Rails.root.join('public', 'system', 'logs')
    FileUtils::mkdir_p(folder)
    name = Digest::MD5.hexdigest("#{Time.now}-#{rand(100)}")
    log_name = File.join(folder, "p99_#{name}.log")
    @log = Log.create(:ip_address => request.remote_ip, :log => log_name)
    FileUtils.mv(params[:upload][:log].tempfile.path, log_name)
    Stalker.enqueue('log.process', {:log => log_name, :id => @log.id}, {:ttr => 1200}) unless Rails.env == 'test'
    session[:uploaded] = true
    redirect_to root_path unless @log.save
  end
  
  def index
    expires_in(1.minute)
    @search = ''
    unless params.include?(:letter)
      params[:letter] = 'a'
    end
    @letter = params[:letter]
    @items = Item.name_starts_with(params[:letter]).order('name ASC').not_hidden
    prepair_items
  end
  
  def destroy
    auction = Auction.find(params[:id])
    expire_page :action => "show", :id => params[:id]
    flash[:notice] = "Auction removed"
    redirect_to :back if auction.hide!
  end
  
  def search
    @search = params[:search][:search]
    @items = Item.search_for(params[:search][:search].downcase).order('name ASC').not_hidden
    prepair_items
    render :action => :index
  end
  
  def show
    redirect_to item_path(params[:id]), :status => 302
  end
  
  
  private
  
  def prepair_items
    @auctions = {}
    @items.each do |item|
      auctions = item.auctions.where(:hidden => false).select('price').map(&:price).to_vector(:scale)
      next if auctions.size < 10
      @auctions[item.name] = auctions
    end
  end
  
end

app/helpers/auction_helper.rb
module AuctionHelper
  
  def letter_pagination(param)
    out = []
    ('a'..'z').to_a.each do |letter|
		  if param == letter
			  out << letter
			else
			  out << link_to(letter, auction_index_path(:letter=>letter))
		  end
	  end
	  out.join("\n").html_safe
  end

end

app/views/auction/create.haml
%p
	%span{:class => 'number'}= @auction_data.item_count
	Items found
	
%p 
	= link_to("View Auction Data", auction_index_path)

app/views/auction/create.html.haml
%p Thank you for uploading your log as been added the the queue for processing!
	
%p 
	= link_to("View Auction Data", auction_index_path)

app/views/auction/index.haml
#auction_data
  %p
    = link_to('Upload a log file', new_auction_path)
  #pagination
    = letter_pagination(@letter)
  %table{:cellspacing => 0, :cellpadding => 5}
    %thead
      %tr
        %th
          Item
        %th
          Avg Price
        %th
          Max
        %th
          Min
        %th 
          Times seen
        %th
          10 Day average
        %th
          30 Day average
        %th
    %tbody
      -	@items.each do |item|
        - next if item.auctions.blank?
        - prices = item.auctions.map{|a| a.price}.compact.sort
        %tr{:class => cycle('alt','')}
          %td 
            = item.name
          %td
            = (prices.inject{ |sum, el| sum + el }.to_f / prices.size).round
          %td
            = prices.last.round
          %td
            = prices.first.round
          %td
            = prices.size
          %td
            - math = item.auctions.average(:price, :conditions => {:time => 10.days.ago..Time.now})
            = math.blank? ? 0.0 : math.round
          %td
            - math = item.auctions.average(:price, :conditions => {:time => 30.days.ago..Time.now})
            = math.blank? ? 0.0 : math.round
          %td 
            = link_to("Remove", auction_path(item, :letter => params[:letter]), :method => :delete)
  #pagination
    = letter_pagination(@letter)

app/views/auction/index.html.haml
- content_for :title do
  - if params[:letter]
    Auctions starting with letter
    = params[:letter].upcase
  - else
    Search Results for 
    = params[:search][:search]
  
#auction_data
  #pagination
    = letter_pagination(@letter)
  %table{:cellspacing => 0, :cellpadding => 5, :class => 'auctions'}
    %thead
      %tr
        %th
          Item
        %th
          Median
        %th
          Mean Price
        %th
          Std Deviation
        %th
          Max
        %th
          Min
        %th 
          Times seen
        %th
          10 Day mean
        %th
          30 Day mean
    %tbody
      - @items.each do |item|
        - next if @auctions[item.name].blank?
        %tr{:class => cycle('alt','')}
          %td 
            = link_to(item.name, item_path(item.id), :item_id => item.id, :class => :item_link)
          %td
            = @auctions[item.name].median
          %td
            = @auctions[item.name].mean.round(2)
          %td
            = @auctions[item.name].sdp.round(2)
          %td
            = @auctions[item.name].max
          %td
            = @auctions[item.name].min
          %td
            = @auctions[item.name].size
          %td
            - math = item.auctions.not_hidden.average(:price, :conditions => {:time => 10.days.ago..Time.now})
            = math.blank? ? 0.0 : math.round
          %td
            - math = item.auctions.not_hidden.average(:price, :conditions => {:time => 30.days.ago..Time.now})
            = math.blank? ? 0.0 : math.round
  #pagination
    = letter_pagination(@letter)

app/views/auction/new.haml
%h1
	Upload a Log File
.form
	- form_for(:upload, :url => auction_index_path, :html => {:multipart => true}) do |f|
		%p=f.file_field :log
		%p=f.submit

app/views/auction/new.html.haml
%h1
  Welcome to the auction upload page
%p  
  In order to upload a log you first need to enable logging in game by typing /log
%p  
  the logs will then be stored in your ever quest directory select the file from below push submit
%p  
  do not worry about duplication the parser accounts for that, you may upload the same log file over and over as you gather data and nothing will be duplicated
.form
  - form_for(:upload, :url => auction_index_path, :html => {:multipart => true}) do |f|
    %p=f.file_field :log
    %p=f.submit

app/views/auction/show.html.haml
%h1
  = @item.name
%p
  Max: 
  = @item.auctions.maximum(:price)
%p
  Min:
  = @item.auctions.minimum(:price)
%p 
  Average:
  = @item.auctions.average(:price)
  
= image_tag("graph/#{@underscored}.png") if @item.auctions.size > 1

%h2
  Auction Data
%table{:cellspacing => 0, :cellpadding => 5}
  %tr
    %th
      Time
    %th
      Price
  - @auctions.each do |auction|
    %tr{:class => cycle('alt','')}
      %td
        = auction.time.strftime("%a %b %d %I:%M %p")
      %td
        = auction.price
= will_paginate @auctions