config/routes.rb
Auctioneer::Application.routes.draw do
  resources :item_aliases

  get '/auctions/search' => 'auction#search', :as => 'auction_search'
  resources :auction
  resources :item
  resources :logs
  root :to => 'auction#index'

end

app/controllers/admin/item_aliases_controller.rb
class Admin::ItemAliasesController < Admin::ResourcesController
  
end

app/controllers/item_aliases_controller.rb
class ItemAliasesController < ApplicationController
  # GET /item_aliases
  # GET /item_aliases.xml
  def index
    @item_aliases = ItemAlias.order('alias').paginate(:page => params[:page], :per_page => 25)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @item_aliases }
    end
  end

  # GET /item_aliases/1
  # GET /item_aliases/1.xml
  def show
    @item_alias = ItemAlias.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item_alias }
    end
  end

  # GET /item_aliases/new
  # GET /item_aliases/new.xml
  def new
    @item_alias = ItemAlias.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item_alias }
    end
  end

  # GET /item_aliases/1/edit
  def edit
    @item_alias = ItemAlias.find(params[:id])
  end

  # POST /item_aliases
  # POST /item_aliases.xml
  def create
    item = params[:item_alias].delete(:item)
    @item_alias = ItemAlias.new(params[:item_alias])
    @item_alias.item = Item.find_by_name(item)
    respond_to do |format|
      if @item_alias.save
        format.html { redirect_to(@item_alias, :notice => 'Item alias was successfully created.') }
        format.xml  { render :xml => @item_alias, :status => :created, :location => @item_alias }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item_alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /item_aliases/1
  # PUT /item_aliases/1.xml
  def update
    item = params[:item_alias].delete(:item)
    @item_alias = ItemAlias.find(params[:id])
    @item_alias.item = Item.find_by_name(item)
    respond_to do |format|
      if @item_alias.update_attributes(params[:item_alias])
        format.html { redirect_to(@item_alias, :notice => 'Item alias was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item_alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /item_aliases/1
  # DELETE /item_aliases/1.xml
  def destroy
    @item_alias = ItemAlias.find(params[:id])
    @item_alias.destroy

    respond_to do |format|
      format.html { redirect_to(item_aliases_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/item_aliases_helper.rb
module ItemAliasesHelper
end

app/views/item_aliases/_form.html.haml
= form_for(@item_alias) do |f|
  - if @item_alias.errors.any?
    #error_explanation
      %h2
        = pluralize(@item_alias.errors.count, "error")
        prohibited this item_alias from being saved:
      %ul
        - @item_alias.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :alias
    %br/
    = f.text_field :alias
  .field
    = f.label :item
    %br/
    = f.text_field :item
  .actions
    = f.submit

app/views/item_aliases/edit.html.haml
%h1 Editing item_alias
= render 'form'
= link_to 'Show', @item_alias
|
\#{link_to 'Back', item_aliases_path}

app/views/item_aliases/index.html.haml
%h1 Listing item_aliases
%table
  %tr
    %th Alias
    %th Item
    %th
    %th
    %th
  - @item_aliases.each do |item_alias|
    %tr
      %td= item_alias.alias
      %td= item_alias.item.name
      %td= link_to 'Show', item_alias
      %td= link_to 'Edit', edit_item_alias_path(item_alias)
      %td= link_to 'Destroy', item_alias, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Item alias', new_item_alias_path
= will_paginate(@item_aliases)

app/views/item_aliases/new.html.haml
%h1 New item_alias
= render 'form'
= link_to 'Back', item_aliases_path

app/views/item_aliases/show.html.haml
%p#notice= notice
%p
  %b Alias:
  = @item_alias.alias
%p
  %b Item:
  = @item_alias.item.name
= link_to 'Edit', edit_item_alias_path(@item_alias)
|
\#{link_to 'Back', item_aliases_path}