config/routes.rb
Auctioneer::Application.routes.draw do
  resources :item_aliases

  get '/auctions/search' => 'auction#search', :as => 'auction_search'
  resources :auction
  resources :item
  resources :logs
  root :to => 'auction#index'

end

app/views/layouts/_popup.html.haml
%h2 HEY!
%p Do you use this site a lot?
%p Would you like this box to go away?
%p Then help out by uploading log files!
%p This site does not function or really matter with out uploaded log files so do you part to make sure it stays up to date
%p 
  %em Hint if you upload a log this box goes away!
  %p=link_to('THIS IS THE UPLOADLINK', new_auction_path)
%p.bold Thanks, Stairs!

app/views/layouts/application.haml
%html
  %head
    = stylesheet_link_tag 'style'
    = javascript_include_tag :all
    %title=@page_title.join(' - ')
  %body
    #wrapper
      #header
        = display_flash
      #content
        = yield
      #footer

app/views/layouts/application.html.haml
!!!
%html
  %head
    = csrf_meta_tag
    = stylesheet_link_tag 'compiled/screen'
    = stylesheet_link_tag 'compiled/pie.css'
    = stylesheet_link_tag 'jquery-ui.css', 'facebox'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/jquery-ui.min.js'
    = javascript_include_tag 'rails', 'application', 'excanvas.min', 'jquery.flot.min', 'facebox'
    
    %title= @page_title = yield :title
  %body{:class => controller_name}
    #header
      #menu
        %h1= link_to "Auction Tracker", root_path
        %ul
          %li= link_to('Home', root_path, :class => 'button')
          %li= link_to('Upload', new_auction_path, :class => 'button')
    #content{:class => action_name}
      #search
        = form_for :search, :url => auction_search_path, :html => {:method => :get} do |f| 
          = f.text_field :search, :value => @search
          = f.submit "Search", :class => 'button'
      - flash.each do |type, message|
        %div{:id=>"flash_#{type}", :class => 'flash'}
          = message
      %h2= @page_title
      = yield
      #footer
        %p
          Comments or sugestions
          = mail_to('stairs@goonquest.com', 'email me', :encode => "javascript")
        - unless @glog.blank?
          %p
            Last log uploaded on 
            = @glog.created_at
        <script type="text/javascript"><!--
        google_ad_client = "pub-0085223469947170";
        /* auction tracker */
        google_ad_slot = "4931544494";
        google_ad_width = 728;
        google_ad_height = 90;
        //-->
        </script>
        <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>
    :javascript
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-18922373-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();